{* TIME IN SECONDS *}
SLIDE_SPEED=10
SLIDE_SPEED_CUSTOM=30
{* THIS ONE IS JUST USED TO CHANGE THE PAGE QUICKLY IF THERE IS NO OUTPUT FOR THE SLIDE, I'LL KEEP IT LIKE THIS IN CASE WE WANT TO ADJUST IT TO SOME NUMBER *}
SLIDE_SPEED_WITHOUT_OUTPUT=5
SLIDE_POSTS_PER_PAGE=14

{* THE UPDATE FREQUENCY (IN SECONDS) OF THE DIV THAT SET THE LOGIN-LAST-ACTIVITY-TIME *}
LOGIN_ACTIVITY_FREQUENCY=99
{* USED TO DISABLE SOME AJAX THINGIES *}
USE_AUTO_SUGGEST_SEARCH=true
USE_AJAX_LOGIN=true

EMAIL_INFO=info@stockholmopen.nu
EMAIL_SO_INFO=info@stockholmopen.nu
EMAIL_SO_PRESS=press@stockholmopen.nu
EMAIL_SO_SUPPORT=support@stockholmopen.nu

MAIN_TELEPHONE=+46 733 103233

MAIN_SNAIL_ADDRESS=The Stockholm Open<br />PAL Communications<br />Kristinebergsvägen 44<br />SE-112 44 STOCKHOLM<br />Sweden

PAYPAL_ADD_PERCENT=3.4
PAYPAL_FEE_SEK=3.25 SEK
PAYPAL_FEE_EUR=0.4 EUR
PAYPAL_FEE_USD=0.5 USD
PAYPAL_FEE_GBP=0.3 GBP

MAIN_TOURNAMENT_ENTRANCE_PRICE_SEK=250 SEK
MAIN_TOURNAMENT_ENTRANCE_PRICE_EUR=29 EUR
MAIN_TOURNAMENT_ENTRANCE_PRICE_USD=37 USD
MAIN_TOURNAMENT_ENTRANCE_PRICE_GBP=24 GBP
MAIN_TOURNAMENT_ENTRY_PRICE_SEK=50 SEK
MAIN_TOURNAMENT_ENTRY_PRICE_EUR=6 EUR
MAIN_TOURNAMENT_ENTRY_PRICE_USD=8 USD
MAIN_TOURNAMENT_ENTRY_PRICE_GBP=5 GBP

SPLIT_TOURNAMENT_ENTRANCE_PRICE_SEK=100 SEK
SPLIT_TOURNAMENT_ENTRANCE_PRICE_EUR=12 EUR
SPLIT_TOURNAMENT_ENTRANCE_PRICE_USD=15 USD
SPLIT_TOURNAMENT_ENTRANCE_PRICE_GBP=10 GBP
SPLIT_TOURNAMENT_ENTRY_PRICE_SEK=20 SEK
SPLIT_TOURNAMENT_ENTRY_PRICE_EUR=2.50 EUR
SPLIT_TOURNAMENT_ENTRY_PRICE_USD=3 USD
SPLIT_TOURNAMENT_ENTRY_PRICE_GBP=2 GBP

CLASSICS_TOURNAMENT_ENTRANCE_PRICE_SEK=100 SEK
CLASSICS_TOURNAMENT_ENTRANCE_PRICE_EUR=12 EUR
CLASSICS_TOURNAMENT_ENTRANCE_PRICE_USD=15 USD
CLASSICS_TOURNAMENT_ENTRANCE_PRICE_GBP=10 GBP
CLASSICS_TOURNAMENT_ENTRY_PRICE_SEK=20 SEK
CLASSICS_TOURNAMENT_ENTRY_PRICE_EUR=2.50 EUR
CLASSICS_TOURNAMENT_ENTRY_PRICE_USD=3 USD
CLASSICS_TOURNAMENT_ENTRY_PRICE_GBP=2 GBP

TSHIRT_PRICE_SEK=100 SEK
TSHIRT_PRICE_EUR=12 EUR
TSHIRT_PRICE_USD=15 USD
TSHIRT_PRICE_GBP=10 GBP

NUMBER_OF_FREE_ENTRIES=3
NUMBER_OF_FREE_ENTRIES_FOREIGN=4
MAX_ENTRIES=12
ADDITIONAL_ENTRIES_SWE=9
ADDITIONAL_ENTRIES_FOREIGN=8

NUMBER_OF_FREE_CLASSICS_ENTRIES=3
NUMBER_OF_FREE_CLASSICS_ENTRIES_FOREIGN=4
MAX_ENTRIES_CLASSICS=12
ADDITIONAL_CLASSICS_ENTRIES_SWE=9
ADDITIONAL_CLASSICS_ENTRIES_FOREIGN=8

NUMBER_OF_FREE_TEAM_ENTRIES=3
NUMBER_OF_FREE_TEAM_ENTRIES_FOREIGN=4
MAX_ENTRIES_TEAM=12
ADDITIONAL_TEAM_ENTRIES_SWE=9
ADDITIONAL_TEAM_ENTRIES_FOREIGN=8

MAX_ENTRIES_TEAM=12
SPLIT_FLIPPER_TOTAL_ENTRIES=12

NO_OF_PLAYERS_IN_FINAL=32
NO_OF_TEAMS_IN_FINAL=8
NO_OF_PLAYERS_IN_CLASSICS_FINAL=24

BANKGIRO_NO=5909-5182
BANKKONTO_FSB_NO=8327-9 903.192.049-0
BANKKONTO_SEB_NO=5267-2992762
IBAN_NO=SE2280000832799031920490
