{* USED TO HIDE THE CURRENT YEAR'S STANDINGS AND STATS IF THE TOURNAMENT HASN'T BEEN STARTED VALUE E.G. 2008 *}
{* THIS WILL HIDE THE SLIDE(SHOW) LINKS TO SINCE IT MAKES NO SENSE TO DISPLAY THEM (SINCE THE SLIDE-LINKS ON THE MENU JUST
STARTS THE CURRENT YEAR'S SLIDES) IF WE DON'T WANT TO SHOW THE STANDINGS *}

// MENU_YEAR_HIDE=2013

MENU_DISPLAY_HOME=true

MENU_DISPLAY_GENERAL=true
MENU_DISPLAY_NEWS=true
MENU_DISPLAY_OVERVIEW=true
MENU_DISPLAY_ENTRANCE_FEE=true
MENU_DISPLAY_GAMES=true
MENU_DISPLAY_PRIZES=false
MENU_DISPLAY_DIVISION=true
MENU_DISPLAY_CLASSICS=true
MENU_DISPLAY_SPLIT=true
MENU_DISPLAY_JUNIORS=false
MENU_DISPLAY_MINI=true

MENU_DISPLAY_RULES=true
MENU_DISPLAY_GENERAL_RULES=true
MENU_DISPLAY_GENERAL_RULES_SPLIT=true
MENU_DISPLAY_QUAL_DETAILS=true
MENU_DISPLAY_FINAL_DETAILS=true

MENU_DISPLAY_LOGISTICS=true
MENU_DISPLAY_LOCATION=true
MENU_DISPLAY_TRAVEL=true
MENU_DISPLAY_ACC=true

MENU_DISPLAY_RESULTS=true

{* SETTING THESE TO FALSE HERE WILL ALSO DISABLE ANY POSSIBILITIES (IN THE PHP-CODE) TO REGISTER *}
{* DISABLING "MENU_DISPLAY_REGISTER" IS SUFFICIENT TO DISABLE ALL REGISTRATION *}
MENU_DISPLAY_REGISTER=false
MENU_DISPLAY_REG_MAIN=true
MENU_DISPLAY_REG_SPLIT=true
MENU_DISPLAY_REG_PLAYERS=true

MENU_DISPLAY_STANDINGS=true

MENU_DISPLAY_FINALS=true

MENU_DISPLAY_STATS=true
MENU_DISPLAY_STATS_YEARLY=true
MENU_DISPLAY_STATS_TOP_ALL_TIME=true
MENU_DISPLAY_BEST_ENTRIES=true

MENU_DISPLAY_MISC=true
MENU_DISPLAY_VOLUNTEER=true
MENU_DISPLAY_VOLUNTEERS=true
MENU_DISPLAY_PROMOTION=true
MENU_DISPLAY_TSHIRT=true
MENU_DISPLAY_PRESS=true
MENU_DISPLAY_VIDEO=true
MENU_DISPLAY_SOCIAL=true
MENU_DISPLAY_STPB=true
MENU_DISPLAY_GALLERY=true
MENU_DISPLAY_SLIDE=true

MENU_DISPLAY_CONTACT=true

{* SETTING THIS TO FALSE WILL DISABLE ALL POSSIBILITIES TO REGISTER ENTRIES, CHANGE SCORES ETC. *}
MENU_DISPLAY_ENTRY_REG=true
MENU_DISPLAY_USER_ACTIVITY=true
